#!/usr/bin/env perl

use strict;
use warnings;
use 5.010;

use DateTime;
#use Smart::Comments;

use DBH;

main(@ARGV);

sub main {
    # Params
    my ($domain, $name, $data) = @_;
    my $type = "A";
    my $dt = DateTime->now(time_zone => 'local');
    my $updatetime = $dt->strftime("%F %T");
    my $dbh = $DBH::dbh;
    ### $dbh
    my $sth;
    my $q1 = <<"SQL";
SELECT
    ddns.name, ddns.type, ddns.data, ddns.updatetime, zone.id
  FROM ddns, zone
  WHERE zone.domain = ? AND ddns.name = ? AND ddns.type = ? AND ddns.zone = zone.id
  ORDER BY updatetime DESC
  LIMIT 1
  FOR UPDATE
SQL
    $sth = $dbh->prepare($q1);
    $sth->execute($domain, $name, $type);
    my $row = $sth->fetchrow_arrayref;
    $sth->finish;
    my $zone_id = 999;  # TOOO: Unknown zone handling
    if ($row) {
        if ($row->[2] eq $data) {
            $dbh->disconnect;
            return;
        }
        $zone_id = $row->[4];
    }
    my $q2 = <<"SQL";
INSERT INTO ddns
(zone, name, type, data, updatetime, applied)
VALUES
(?, ?, ?, ?, ?, ?)
SQL
    $sth = $dbh->prepare($q2);
    $sth->execute($zone_id, $name, $type, $data, $updatetime, 0);
    $sth->finish;
    $dbh->commit;
    $dbh->disconnect;
};

